# Generated by Django 4.0.4 on 2022-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('deal_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('saving', models.IntegerField()),
                ('thumb', models.URLField()),
                ('store_id', models.IntegerField()),
            ],
        ),
    ]
