# Generated by Django 4.0.4 on 2022-05-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoGamesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='deal_id',
            field=models.CharField(max_length=200),
        ),
    ]
